### ISSUE TITLE
About the init parameter

### ISSUE THREAD

**Issue by TOUBH** [gcerar/pytorch-neural-style-transfer#1]
Author, your work is great! However, I have a problem. When I set the init parameter to noise, that is, start training with a noise map, and the final result is still a noise map, such as the following figure:
![image](https://user-images.githubusercontent.com/125473669/229352685-ec63bf86-b54d-46e6-b7ec-d984a34e5b2c.png)
Looking forward to your reply!

**Comment by gcerar** [comment]
Hey @unhker. Can you please explain what your expectations were? I want to make sure we are on the same page.

Simply put, the code takes **noise as input** and applies desired **style** to that noise. Since there are no specific features on a noisy image, the output is also noise :).

**Comment by unhker** [comment]
> Hey @unhker. Can you please explain what your expectations were? I want to make sure we are on the same page.
> 
> Simply put, the code takes **noise as input** and applies desired **style** to that noise. Since there are no specific features on a noisy image, the output is also noise :).

Glad to receive your reply! I'm sorry I didn't express myself clearly.

I use this command to explain: 'python style -- input bridge. jpg -- style start right. jpg -- input noise', that is, the output image is initialized with a noise image. The expectation is that the final output image captures both the style of the style image and the content of the content image. However, after the program completes execution, the output image only learns the style of the style image, but does not capture the content of the content image. That is, it still looks like a noisy image, just like the image I posted above. I cannot determine where the problem is :).

**Comment by unhker** [comment]
Glad to receive your reply! I'm sorry I didn't express myself clearly.

I use this command to explain: 'python style -- input bridge. jpg -- style start right. jpg -- input noise', that is, the output image is initialized with a noise image. The expectation is that the final output image captures both the style of the style image and the content of the content image. However, after the program completes execution, the output image only learns the style of the style image, but does not capture the content of the content image. That is, it still looks like a noisy image, just like the image I posted above. I cannot determine where the problem is :).

**Comment by TOUBH** [comment]
Glad to receive your reply! I'm sorry I didn't express myself clearly.

I use this command to explain: ' python style --input bridge. jpg --style starry-night. jpg --input noise ', that is, the output image is initialized with a noise image. The expectation is that the final output image captures both the style of the style image and the content of the content image. However, after the program completes execution, the output image only learns the style of the style image, but does not capture the content of the content image. That is, it still looks like a noisy image, just like the image I posted above. I cannot determine where the problem is :).

**Comment by gcerar** [comment]
I think it should work. Try playing with the `CONTENT_WEIGHT`, `STYLE_WEIGHT,` and `TV_WEIGHT` constants to achieve the desired result. Try setting content weights to something very high, 1e9, for instance, and set style and variation to something low. See [Aleksa's README](https://github.com/gordicaleksa/pytorch-neural-style-transfer#contentstyle-tradeoff) for reference.
